#!/usr/bin/python -u
#
# readlog - cuts apache log into pieces
# Pipe apache logs into readlog to selectively display interesting information.
# 
# Example: show the access time as Unix epoch and ip addresses
# 
# cat /var/log/apache2/access.log | ./readlog --columns=time,ips
# 
# See http://github.com/xwz/readlog

import sys
from optparse import OptionParser
from log_reader import ApacheReader
import urlparse
import cgi
import datetime
import time

default_columns = [
    'ips', 
    'username', 
    'ident', 
    'time', 
    'tz', 
    'method',
    'url',
    'path', 
    'query',
    'fragment',
    'protocol', 
    'status', 
    'size',
    'referer', 
    'user-agent', 
]

def cli_options():
    parser = OptionParser()
    parser.add_option("-c", "--columns", dest="columns", 
            help="comma delimited list of columns, available columns: %s" % ", ".join(default_columns))
    parser.add_option("-p", "--params", dest="params",
            help="comma delimited list of query parameter names")
    parser.add_option("-d", "--date", dest="date",
            help="date format, default is unixtimestamp")
    parser.add_option("-f", "--format", dest="format",
            help="log format, accepts 'common', 'combined' and custom format string")
    options, args = parser.parse_args()
    if options.columns:
        columns = options.columns.split(",")
    else:
        columns = []
    if options.params:
        params = options.params.split(",")
    else:
        params = []
    if len(params)==0 and len(columns)==0:
        columns = default_columns
    return columns, params, options.date, options.format
    
def readlog(columns, params, dateformat, logformat):
    if logformat=="common":
        logformat = ApacheReader.COMMON
    elif logformat=="combined" or not logformat:
        logformat = ApacheReader.COMBINED

    for log in ApacheReader(sys.stdin, logformat):
        log["ips"] = ",".join(log["ips"])
        if log["time"]:
            if dateformat:
                log["time"] = log["time"].strftime(dateformat)
            else:
                log["time"] = "%d" % time.mktime(log["time"].timetuple())            
        url = urlparse.urlparse(log["path"])
        log["url"] = log["path"]
        log["path"] = url.path
        log["query"] = url.query
        log["fragment"] = url.fragment
        query = dict(cgi.parse_qsl(url.query, True))
        info = [log[col] for col in columns if col in log]
        info = info + [query[param] for param in params if param in query]
        print " ".join(str(i) for i in info)

if __name__ == "__main__":
    columns, params, dateformat, logformat = cli_options()
    readlog(columns, params, dateformat, logformat)
